### PR TITLE
Remove extraneous semicolon

### PR DESCRIPTION
**Pull request by mderriey**
Also standardise to 4-space indentation, which I'm happy to undo if you want to keep the PR focused to a single thing 🙏

### CODE REVIEW

**Comment by mderriey** [comment]
Another thing I noticed is the README states:

> To verify if a message is logged multiple times use `AppearsTimes(int numberOfTimes)`

However, all the examples use the `Appearing().Times(int numberOfTimes)`.
I'm not sure whether both APIs are available, or if it's an old API that has now been removed.

**Comment by sandermvanvliet** [comment]
Hi @mderriey!
Thanks for this 👍 Always great to get some documentation improvements.

I've had a look but indeed `AppearsTimes` is very old and has been gone for quite some time. Completely missed it that it was still in the README.
If you want to change that to `Appearing().Times(...)` that would be awesome, otherwise I can do it too.

**Comment by mderriey** [comment]
Hey @sandermvanvliet 👋

No problem at all, I just pushed another commit to update `AppearTimes()` to `Appearing().Times()`.

Cheers 🙏

**Comment by mderriey** [comment]
Feel free to squash and update the commit message when merging now that it's not just about the semicolon 😉

**Comment by sandermvanvliet** [comment]
Cool 👍 Thanks a bunch!

**Pull request merged**
